-- Create cars table
CREATE TABLE IF NOT EXISTS cars (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  price_per_day NUMERIC(10, 2) NOT NULL,
  image TEXT,
  category TEXT NOT NULL,
  transmission TEXT NOT NULL,
  fuel_type TEXT NOT NULL,
  seats INTEGER NOT NULL,
  luggage_capacity INTEGER NOT NULL,
  features TEXT[] DEFAULT '{}',
  rating NUMERIC(3,1) DEFAULT 0,
  reviews_count INTEGER DEFAULT 0,
  provider TEXT NOT NULL,
  location TEXT NOT NULL
);

-- Insert sample data
INSERT INTO cars (name, description, price_per_day, image, category, transmission, fuel_type, seats, luggage_capacity, features, rating, reviews_count, provider, location)
VALUES 
  (
    'Toyota Yaris',
    'Compact and fuel-efficient car, perfect for navigating narrow island roads. Includes air conditioning and Bluetooth connectivity.',
    35.00,
    'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?ixlib=rb-4.0.3',
    'economy',
    'manual',
    'petrol',
    5,
    2,
    ARRAY['Air Conditioning', 'Bluetooth', 'USB Port', 'Power Steering'],
    4.5,
    87,
    'Cyclades Car Rentals',
    'Mykonos'
  ),
  (
    'Fiat 500',
    'Stylish and compact city car with excellent fuel economy. Ideal for couples exploring the islands.',
    40.00,
    'https://images.unsplash.com/photo-1588636142475-a62d56692870?ixlib=rb-4.0.3',
    'economy',
    'manual',
    'petrol',
    4,
    1,
    ARRAY['Air Conditioning', 'Radio', 'Power Windows', 'Central Locking'],
    4.3,
    65,
    'Island Wheels',
    'Paros'
  ),
  (
    'Hyundai i20',
    'Reliable and spacious hatchback with good fuel efficiency. Great for small families or groups.',
    45.00,
    'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?ixlib=rb-4.0.3',
    'economy',
    'manual',
    'petrol',
    5,
    2,
    ARRAY['Air Conditioning', 'Bluetooth', 'USB Port', 'AUX Input', 'Power Steering'],
    4.4,
    92,
    'Blue Aegean Rentals',
    'Santorini'
  ),
  (
    'Peugeot 208',
    'Modern compact car with stylish design and comfortable interior. Excellent for island exploration.',
    48.00,
    'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?ixlib=rb-4.0.3',
    'compact',
    'automatic',
    'petrol',
    5,
    2,
    ARRAY['Air Conditioning', 'Bluetooth', 'Touch Screen', 'Cruise Control', 'Parking Sensors'],
    4.6,
    78,
    'Greek Island Motors',
    'Naxos'
  ),
  (
    'Volkswagen Golf',
    'Well-built compact car with excellent handling and comfort. Perfect balance of performance and practicality.',
    55.00,
    'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?ixlib=rb-4.0.3',
    'compact',
    'automatic',
    'petrol',
    5,
    3,
    ARRAY['Air Conditioning', 'Bluetooth', 'Touch Screen', 'Cruise Control', 'Parking Sensors', 'Navigation'],
    4.7,
    103,
    'Cyclades Car Rentals',
    'Mykonos'
  ),
  (
    'Nissan Qashqai',
    'Compact SUV with higher ground clearance, perfect for exploring more remote areas of the islands.',
    65.00,
    'https://images.unsplash.com/photo-1580273916550-e323be2ae537?ixlib=rb-4.0.3',
    'suv',
    'automatic',
    'diesel',
    5,
    4,
    ARRAY['Air Conditioning', 'Bluetooth', 'Touch Screen', 'Cruise Control', 'Parking Sensors', 'Navigation', 'Rear Camera'],
    4.8,
    89,
    'Blue Aegean Rentals',
    'Santorini'
  ),
  (
    'Jeep Renegade',
    'Compact SUV with rugged capabilities, ideal for exploring off-the-beaten-path locations.',
    70.00,
    'https://images.unsplash.com/photo-1533106418989-88406c7cc8ca?ixlib=rb-4.0.3',
    'suv',
    'automatic',
    'diesel',
    5,
    4,
    ARRAY['Air Conditioning', 'Bluetooth', 'Touch Screen', 'Cruise Control', 'Parking Sensors', 'Navigation', 'Rear Camera', '4x4'],
    4.6,
    76,
    'Greek Island Motors',
    'Naxos'
  ),
  (
    'Mercedes-Benz A-Class',
    'Premium compact car with luxurious interior and advanced technology features.',
    85.00,
    'https://images.unsplash.com/photo-1617814076668-8dfc6fe2d602?ixlib=rb-4.0.3',
    'luxury',
    'automatic',
    'petrol',
    5,
    3,
    ARRAY['Air Conditioning', 'Bluetooth', 'Touch Screen', 'Cruise Control', 'Parking Sensors', 'Navigation', 'Rear Camera', 'Leather Seats', 'Premium Sound System'],
    4.9,
    62,
    'Luxury Island Cars',
    'Mykonos'
  ),
  (
    'BMW 3 Series',
    'Sporty luxury sedan with excellent driving dynamics and premium features.',
    95.00,
    'https://images.unsplash.com/photo-1555215695-3004980ad54e?ixlib=rb-4.0.3',
    'luxury',
    'automatic',
    'petrol',
    5,
    3,
    ARRAY['Air Conditioning', 'Bluetooth', 'Touch Screen', 'Cruise Control', 'Parking Sensors', 'Navigation', 'Rear Camera', 'Leather Seats', 'Premium Sound System', 'Sunroof'],
    4.9,
    58,
    'Luxury Island Cars',
    'Santorini'
  ),
  (
    'Suzuki Jimny',
    'Compact 4x4 with excellent off-road capabilities, perfect for exploring rugged terrain.',
    60.00,
    'https://images.unsplash.com/photo-1594132599108-3e5cb99c5c40?ixlib=rb-4.0.3',
    'suv',
    'manual',
    'petrol',
    4,
    2,
    ARRAY['Air Conditioning', 'Bluetooth', 'USB Port', '4x4', 'Power Steering'],
    4.5,
    94,
    'Cyclades Auto',
    'Milos'
  ),
  (
    'Citroen C3',
    'Quirky and comfortable compact car with distinctive styling and good fuel economy.',
    42.00,
    'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?ixlib=rb-4.0.3',
    'economy',
    'manual',
    'petrol',
    5,
    2,
    ARRAY['Air Conditioning', 'Bluetooth', 'USB Port', 'Touch Screen', 'Parking Sensors'],
    4.4,
    72,
    'Island Wheels',
    'Paros'
  ),
  (
    'Audi A3',
    'Premium compact car with refined interior and sporty performance.',
    80.00,
    'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?ixlib=rb-4.0.3',
    'luxury',
    'automatic',
    'petrol',
    5,
    3,
    ARRAY['Air Conditioning', 'Bluetooth', 'Touch Screen', 'Cruise Control', 'Parking Sensors', 'Navigation', 'Rear Camera', 'Leather Seats'],
    4.8,
    64,
    'Luxury Island Cars',
    'Mykonos'
  )
ON CONFLICT (id) DO NOTHING;
